version: 2
jobs:
  test-8.0.2:
    docker:
      - image: library/haskell:8.0.2
    steps:
      - restore_cache:
          keys: 
            - stack-ghc-8.0.2-{{ arch }}-{{ checksum "stack-8.0.2.yaml" }}
      - checkout
      - run: stack test --stack-yaml=stack-8.0.2.yaml
      - save_cache:
          key: stack-ghc-8.0.2-{{ arch }}-{{ checksum "stack-8.0.2.yaml" }}
          paths:
            - /root/.stack

  test-8.2.2:
    docker:
      - image: library/haskell:8.0.2 # because library/haskell does not have 8.2.2 yet
    steps:
      - restore_cache:
          keys:
            - stack-ghc-8.2.2-{{ arch }}-{{ checksum "stack-8.2.2.yaml" }}
      - checkout
      - run: stack test --stack-yaml=stack-8.2.2.yaml
      - save_cache:
          key: stack-ghc-8.2.2-{{ arch }}-{{ checksum "stack-8.2.2.yaml" }}
          paths:
            - /root/.stack

workflows:
  version: 2
  test:
    jobs:
      - test-8.0.2
      - test-8.2.2